FROM node:16-alpine
WORKDIR /app

# dependencies
COPY package*.json ./
RUN npm ci --only=production

# copy all source files
COPY ./src ./

# set a static port
ENV PORT=8080
EXPOSE 8080

# run app
CMD node index.js
